"""Initial migration.

Revision ID: b4837bc42716
Revises: 
Create Date: 2025-05-01 22:35:33.849406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4837bc42716'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_table')
    op.drop_table('temp_coordinates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_coordinates',
    sa.Column('School_AGE_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('coordinates', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.PrimaryKeyConstraint('School_AGE_ID'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('new_table',
    sa.Column('School_AGE_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('non_English', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('English', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('not_stated', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('School_AGE_ID'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
