name: Deploy Flask Backend to EC2

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2 and Run Flask
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~
          rm -rf 5120-main
          git clone https://github.com/StevenT899/tp21-main.git 5120-main
          cd 5120-main/backend
          pip3 install -r requirements.txt

          echo "🛑 Killing any existing process on port 5000..."
          sudo kill -9 $(sudo lsof -t -i :5000) || true

          echo "🚀 Starting Flask server..."
          nohup python3 main.py > log.out 2>&1 &
